### ISSUE TITLE
Check remaining plant survey datasets from ecoblender datasets

### ISSUE THREAD

**Issue by cjlortie** [cjlortie/desert.species.classification#1]
- [x] shrub contrast dataset (chris)
- [x] Panoche surveys (former ones) (alex)
- [x] former MNP surveys from other years (chris)

**Comment by afilazzola** [comment]
confirmed and added missing species. With the exception of "A.tuberosa" which I am not sure which species it is supposed to be.

**Comment by afilazzola** [comment]
In general, with shrub contrast I believe it remained cumulative our list and should likely include all the species. For Panoche all the species I have found are there now

**Comment by cjlortie** [comment]
thanks, so no other Panoche ones then. super.
found the tuber.. haha.
https://www.wildflower.org/plants/result.php?id_plant=astu

**Comment by cjlortie** [comment]
Asclepias tuberosa  L.

**Comment by cjlortie** [comment]
E.minutiflora
H.vulgare
L.lasiocarpa
